### ISSUE TITLE
Text on latest OSX version is tiny

### ISSUE THREAD

**Issue by ericbrown** [n2qzshce/ham-radio-sync#21]
Text on latest OSX version (v 1.6.0.183) doesn't scale right.

Running on a *scaled* 2560x1440 monitor.  Sidebar text looks fine on a 'standard' 2560x1440 monitor but menu text is huge. Not sure if its worth fixing but figured its worth noting.

Scaled monitor:
<img width="1264" alt="Screen Shot 2021-03-30 at 11 02 28 AM" src="https://user-images.githubusercontent.com/449599/113027632-8da46980-9147-11eb-8ee1-02a3f20cccb9.png">

Standard monitor:

![Screen Shot 2021-03-30 at 11 01 45 AM](https://user-images.githubusercontent.com/449599/113027550-749bb880-9147-11eb-9109-bfd0ba10414f.png)

**Comment by n2qzshce** [comment]
oh wow, thank you!

**Comment by ericbrown** [comment]
Happy to test things out.

**Comment by n2qzshce** [comment]
Could you try this release candidate?
https://github.com/n2qzshce/ham-radio-sync/actions/runs/712731709

**Comment by ericbrown** [comment]
Much better.     Menus are great on both screens. the left side text and interior text (logging text) still changes size on the different screens but is 100% usuable.

scaled screen
<img width="1699" alt="Screen Shot 2021-04-02 at 2 55 51 PM" src="https://user-images.githubusercontent.com/449599/113453654-ade05c80-93c3-11eb-8789-b85636f21b9d.png">

Standard Screen
![Screen Shot 2021-04-02 at 2 56 01 PM](https://user-images.githubusercontent.com/449599/113453667-b5076a80-93c3-11eb-805c-cdd6a5c99972.png)

**Comment by n2qzshce** [comment]
Fixed in 1.6.1.213
